### PR TITLE
Maintenance plugin

### LINKED ISSUE #35: Maintenance plugin.

### PR DESCRIPTION
**Pull request by pgiraud**
Fixes #35

### CODE REVIEW

**Comment by julmon** [comment]
@pgiraud on table view, the `Heap`  and `Indexes` sizes displayed include bloat size. that's why the bar is not right.

**Comment by julmon** [comment]
Little issue with collapsed menu bar:
maint-collapse-menu

**Comment by julmon** [comment]
On schema and table view, bloat bar (stripped blue) does not appear:
maint-schema-no-bloat-indic

**Comment by pgiraud** [comment]
> In index table, what the third column is supposed to show:

It shows the scans count.

**Comment by pgiraud** [comment]
> Little issue with collapsed menu bar:

Fixed 

> On schema and table view, bloat bar (stripped blue) does not appear:

Fixed.

**Comment by julmon** [comment]
Could you please initiate `docs/temboard-upgrade-2-3.0.md` file and put some lines about `temboard.conf` and `temboard-agent.conf` files migration ?

**Pull request merged**
