### PR TITLE
Create Group when adding new Instance

### LINKED ISSUE #187: Auto-register fails if "local_instances" group doesn't exist
Please close the current issue if this is intended.

`temboard-agent-register` is called with `--groups local_instances`. This group may not be available in temboard UI reposistory database.
In my opinion, this should not prevent the agent to auto register.

### PR DESCRIPTION
**Pull request by julmon**
Intends to fix #187

### CODE REVIEW

**Comment by pgiraud** [comment]
So your idea is to create the group if it doesn't exist already.
Crossing fingers that the user didn't make a typo otherwise a new group will be created unintentionaly.

I don't disagree with it. Your patch doesn't work however. `session.merge` needs to be changed to `session.add`.

**Comment by julmon** [comment]
@pgiraud `session.merge` works here, even if the group didn't previously exist.

**Comment by pgiraud** [comment]
Here's the command I use:
```
sudo -u postgres temboard-agent-register --host 0.0.0.0 --port 2345 --groups foo https://172.17.0.1:8888
```
And here's the error I get in the UI console:
```
2018-06-15 15:59:15,974 [temboardui      ] ERROR: Group 'foo' ('instance') does not exist.
2018-06-15 15:59:15,974 [temboardui      ] ERROR: Traceback (most recent call last):
2018-06-15 15:59:15,974 [temboardui      ] ERROR:   File "/home/pierre/work/temboard/temboardui/handlers/base.py", line 130, in func_wrapper
2018-06-15 15:59:15,974 [temboardui      ] ERROR:     return func(self, *args, **kwargs)
2018-06-15 15:59:15,974 [temboardui      ] ERROR:   File "/home/pierre/work/temboard/temboardui/handlers/settings/instance.py", line 189, in post_instance
2018-06-15 15:59:15,974 [temboardui      ] ERROR:     instance.agent_port, group_name)
2018-06-15 15:59:15,974 [temboardui      ] ERROR:   File "/home/pierre/work/temboard/temboardui/application.py", line 424, in add_instance_in_group
2018-06-15 15:59:15,974 [temboardui      ] ERROR:     400, "Group '%s' ('instance') does not exist." % (group_name))
2018-06-15 15:59:15,974 [temboardui      ] ERROR: TemboardUIError: Group 'foo' ('instance') does not exist.
```

**Comment by julmon** [comment]
> Crossing fingers that the user didn't make a typo otherwise a new group will be created unintentionaly.

I think we'll have to live with it. :smile_cat: 

Could you retry with https://github.com/dalibo/temboard/pull/362/commits/c7a7c03515ea4f4be860b8a5a597a00d37f87100 ?

**Pull request merged**
