### PR TITLE
Layout reworking

### PR DESCRIPTION
**Pull request by pgiraud**
The aim of this pull request is to re-organize the layout of the application. The main goal is to make sure it's easier to understand the difference between per-instance functionnalities and application level administrator features.

Work still need to be done to give the tool a visual identity (colors, etc...).
Also "manage" should be changed to "settings" ( #80 ) and "settings" plugin should be remaned "configuration" ( #75 ).

Here are some before/after screen shots:
127 0 0 1-8888-home
127 0 0 1-8888-manage-instances
127 0 0 1-8888-server-temboard-agent-96-2345-dashboard
127 0 0 1-8888-server-temboard-agent-96-2345-activity-running
127 0 0 1-8888-server-temboard-agent-96-2345-supervision-day 2
127 0 0 1-8888-server-temboard-agent-96-2345-settings-configuration

### CODE REVIEW

**Comment by bersace** [comment]
:+1: 

Il y a un champ de recherche à droite (instances) et un à gauche (settings). Je vois bien une PR pour harmoniser ça :)

Lundi, je teste tout ça !

**Comment by pgiraud** [comment]
> Il y a un champ de recherche à droite (instances) et un à gauche (settings). Je vois bien une PR pour harmoniser ça :)

Though I agree that consistency is important, I'd keep it different (position and styling) because:
 - we are dealing with different components (table vs. list),
 - the behavior is different: on-the-fly filtering on key stroke vs. submitted form.

**Comment by bersace** [comment]
In agent login page, i don't have *Manage* nor *me* top right items in the *headerbar*. Am i missing something ?

relecture-pr-81

**Comment by pgiraud** [comment]
> In agent login page, i don't have Manage nor me top right items in the headerbar. Am i missing something ?

I figured this out as well. Issue already created: #79

**Pull request merged**
