### PR TITLE
WIP - Add RHEL/CentOS 8 packaging

### PR DESCRIPTION
**Pull request by OrioQuezac**

### CODE REVIEW

**Comment by FelixSchwarz** [comment]
Do you plan to submit this spec file to Fedora EPEL? If so I can help you with some packaging improvements/lend a hand for the review process.

I just had a quick glance at the spec but I have two comments:

- Try to use Python 3.6 when packaging for RHEL 8. Python 2 is delivered via a module which will go EOL much earlier than RHEL 8 itself.
- CentOS 7+8 have dynamic requirements for Python now so you should not have to list these.
- For CentOS 8 you can also try if dynamic build requirements are supported (not sure from the top of my head). They are in Fedora but I'm not sure if we already support that in EPEL.

**Comment by bersace** [comment]
@FelixSchwarz this PR is superseded by #914  and other. temBoard 7.7 is currently landing in https://yum.dalibo.org/labs for CentOS 7 & 8. Can you give it a try ?

**Comment by FelixSchwarz** [comment]
> temBoard 7.7 is currently landing in https://yum.dalibo.org/labs for CentOS 7 & 8. Can you give it a try ?

@bersace Is it possible to get the actual src.rpm used to build these RPMs?

**Comment by bersace** [comment]
Hi @FelixSchwarz, we do not produce src.rpm.

**Pull request closed without merging**
