### PR TITLE
Convert user settings page to SFC

### PR DESCRIPTION
**Pull request by MarionGiusti**

### CODE REVIEW

**Comment by pgiraud** [comment]
From a very first quick test, I figured out that in some cases, the password fields are not emptied. They should be blank everytime a modal window with the user form is shown.
Steps to reproduce :
 - click on the button to update user "bob",
 - type something in one of the password fields,
 - cancel or close the modal,
 - click on the button to update user "alice".

At this point, an error will be raised whenever you try to click on the "update" button.

**Comment by MarionGiusti** [comment]
Thanks, I hadn't managed to clean up the password when you don't save the form data. I reproduced it following the steps but I didn't see any error in the console. I tried to fixe the clean up but I'm not sure that my solution is very elegant...

**Comment by pgiraud** [comment]
> Thanks, I hadn't managed to clean up the password when you don't save the form data. I reproduced it following the steps but I didn't see any error in the console. I tried to fixe the clean up but I'm not sure that my solution is very elegant...

I don't think this should be done when clicking on the submit button. Nor should it be when submitting the form. If there's an error in the form (for example, that the username is already taken), the password information will be lost and the user will have to type it again.

What would be possible is to listen to the "dismiss" event on the modal window instead of listening to "click" events on button. For example, it's possible to dismiss (close) the modal by clicking on the "cross" at the top right and I don't think you take this possibility into account. The problem is that the UserForm component doesn't know anything about a modal. Unless you find a way to expose a "dismiss" function that the parent would call on modal dismiss.

But, in my opinion, a reset of the password fields could probably be done in the `onUpdated` function. To be checked.

**Comment by pirlgon** [comment]
`onUpdated` is called every time an input changes, so the password will be constantly cleared.
`watchEffect` is called every time the props change, it may be a better place to reset the password.
I'm not sure if the `onUpdated` is needed at all, could we just render multiselect on the `watchEffect` ?
And in fact i think a watch on `props.user.username` might be a better solution, at the moment watchEffect is called more than once when modal is opened.

**Pull request merged**
