### PR TITLE
Alerting stage 3

### PR DESCRIPTION
**Pull request by julmon**
Refactoring alerting mecanisme:
1. We don't store anymore the whole history of alerting checks, we store
only the changes.
2. 'threshold_w' and 'threshold_c' attributes are renamed to 'warning'
and 'critical'.
3. Return check results history as JSON format (array of array).

### CODE REVIEW

**Comment by julmon** [comment]
# HTTP API

## Current state

``` console
$ curl -s -k --cookie "temboard=..."  \
   https://temboard-ui-centos7:8888/server/192.168.122.21/2345/alerting/json/state | python -m json.tool

[
    {
        "state": "OK",
        "name": "archive_ready",
        "key": ""
    },
    {
        "state": "OK",
        "name": "cpu",
        "key": "cpu0"
    },
    {
        "state": "OK",
        "name": "fs",
        "key": "/"
    },
    {
        "state": "OK",
        "name": "fs",
        "key": "/boot"
    },
....
]
```

## Checks list

``` console
$ curl -s -k --cookie "temboard=..." \
https://temboard-ui-centos7:8888/server/192.168.122.21/2345/alerting/json/checks | python -m json.tool

[
    {
        "description": "WAL files ready to be archived",
        "warning": 10.0,
        "enabled": true,
        "name": "archive_ready",
        "criticial": 20.0
    },
    {
        "description": "CPU usage",
        "warning": 50.0,
        "enabled": true,
        "name": "cpu",
        "criticial": 80.0
    },
    {
        "description": "File systems usage (%)",
        "warning": 80.0,
        "enabled": true,
        "name": "fs",
        "criticial": 90.0
    },
...
]
```

## Update Check (`enabled`, `thresholds` or `description`)

``` console
$ curl -D - -k --cookie "temboard=..." \
-X POST --data '{"checks":[{"name":"fs","enabled":1,"description":"File systems usage (%)", "warning": 70}]}' \
https://temboard-ui-centos7:8888/server/192.168.122.21/2345/alerting/json/checks
HTTP/1.1 200 OK
Date: Tue, 24 Apr 2018 08:40:58 GMT
Content-Length: 2
Content-Type: application/json
Server: TornadoServer/4.5.3

{}
```

## Check results history

``` console
$ curl -s -k --cookie "temboard=..." \
https://temboard-ui-centos7:8888/server/192.168.122.21/2345/alerting/json/results/loadaverage\?start\=2018-04-23T00:00:00Z\&end\=2018-04-25T00:00:00Z | python -m json.tool

[
    [
        "2018-04-24T10:20:52+02:00",
        "OK",
        "",
        0.28,
        0.5,
        1
    ],
    [
        "2018-04-24T10:19:51+02:00",
        "WARNING",
        "",
        0.75,
        0.5,
        1
    ],
    [
        "2018-04-24T10:14:49+02:00",
        "CRITICAL",
        "",
        2.6,
        0.5,
        1
    ],
    [
        "2018-04-24T10:08:48+02:00",
        "OK",
        "",
        0.46,
        0.5,
        1
    ],
    [
        "2018-04-24T10:05:47+02:00",
        "CRITICAL",
        "",
        2.18,
        0.5,
        1
    ]
]
```

**Comment by pgiraud** [comment]
As far as I understand, the threshold changes are stored as part of the state changes. This doesn't like a good idea IMO.

First because this looks like a workaround. You use the check scheduled task to detect threshold changes though this could be done via the check service when the check is modified.

"Alerts" (ie. state change) over time is a different information than threshold changes. It should be sent differently to the client. This would make things easier to deal with.

On a different topic: I think "results" in the URL isn't really meaningful. What about "state_change"?

**Comment by julmon** [comment]
Thanks for your review @pgiraud ! Just updated the PR according to your comment. The API is now:

**Check list** : `GET /server/<address>/<port>/alerting/checks.json` 
Ex:
```shell
$ curl -s -k --cookie "temboard=..." \
https://temboard-ui-centos7:8888/server/192.168.122.21/2345/alerting/checks.json | python -m json.tool
[
    {
        "description": "WAL files ready to be archived",
        "warning": 10.0,
        "enabled": true,
        "name": "archive_ready",
        "criticial": 20.0
    },
   ...
]
```

**Update Check (`enabled`, `thresholds` or `description`)** : `POST /server/<address>/<port>/alerting/checks.json`
Ex:
```shell
$ curl -D - -k --cookie "temboard=..." \
-X POST --data '{"checks":[{"name":"cpu","warning":70},{"name":"fs","enabled":false}]}' \             
https://temboard-ui-centos7:8888/server/192.168.122.21/2345/alerting/checks.json

HTTP/1.1 200 OK
Date: Wed, 25 Apr 2018 13:15:57 GMT
Content-Length: 2
Content-Type: application/json
Server: TornadoServer/4.5.3

{}
```

**Check changes history**: `GET /server/<address>/<port>/alerting/check_changes/<check_name>.json`

Ex:
```shell
$ curl -s -k --cookie "temboard=..." \  
https://temboard-ui-centos7:8888/server/192.168.122.21/2345/alerting/check_changes/loadaverage.json | python -m json.tool

[
    [
        "2018-04-25T14:39:10.40869+02:00",
        true,
        0.5,
        1,
        "Loadaverage"
    ]
]

```

**Current State**: `GET /server/<address>/<port>/alerting/state.json`

Ex:
```shell
$ curl -s -k --cookie "temboard=..." \
https://temboard-ui-centos7:8888/server/192.168.122.21/2345/alerting/state.json | python -m json.tool

[
    {
        "state": "OK",
        "name": "archive_ready",
        "key": ""
    },
    {
        "state": "OK",
        "name": "cpu",
        "key": "cpu0"
    },
    {
        "state": "OK",
        "name": "fs",
        "key": "/"
    },
   ...
]
```

**State changes history**: `GET /server/<address>/<port>/alerting/state_changes/<check_name>.json`

Ex:
```shell
$ curl -s -k --cookie "temboard=..." \
https://temboard-ui-centos7:8888/server/192.168.122.21/2345/alerting/state_changes/loadaverage.json | python -m json.tool

[
    [
        "2018-04-25T14:45:12+02:00",
        "OK",
        "",
        0.3,
        0.5,
        1
    ],
    [
        "2018-04-25T14:44:12+02:00",
        "WARNING",
        "",
        0.51,
        0.5,
        1
    ],
  ...
]
```

Filtering by `key`:
``` shell
$ curl -s -k --cookie "temboard=..." \
https://temboard-ui-centos7:8888/server/192.168.122.21/2345/alerting/state_changes/fs.json\?key\=/ | python -m json.tool

[
    [
        "2018-04-25T14:37:09+02:00",
        "OK",
        "/",
        12,
        80,
        90
    ]
]
```

**Comment by pgiraud** [comment]
I have one last request: in the `check_changes` we need to have the values for the `start` and `end` dates even if there was no actual change within the date range.

**Comment by pgiraud** [comment]
Please forget my last comment, I can't reproduce.

**Pull request merged**
