### PR TITLE
Improve collector messages

### PR DESCRIPTION
**Pull request by bersace**
To help issues like #952, #928 , etc.

```
...
 INFO: Starting collector scheduler.                                                                                
 INFO: Scheduling collector for agent 0.0.0.0:2345.                                                                 
 INFO: End of collector scheduler.                                                                                  
 INFO: Starting collector for 0.0.0.0:2345.                                                                                                                                                                                             
 INFO: Discovering hostname from agent 0.0.0.0:2345.                                                                
 INFO: Found host #1 and instance #1 for agent 0.0.0.0:2345, hostname postgres.dev.                                                                                                                                                      
 INFO: Querying monitoring history from agent 0.0.0.0:2345.       
 INFO: Update the inventory for 0.0.0.0:2345.                                                                                                                                                                                           
 INFO: Insert instance availability for 0.0.0.0:2345.                                                                                                                                                                                   
 INFO: Insert collected metrics for 0.0.0.0:2345.                                                                                                                                                                                       
 INFO: Populate checks for host: postgres.dev.                                                                      
 INFO: Apply alerting checks against preprocessed data for agent 0.0.0.0:2345.             
...
```

```
  INFO: End of collector scheduler.                                                                                                
 DEBUG: Job schedule_collector is dead                                                                                             
 DEBUG: Job output : {'type': (5,), 'content': None}                                                                               
 DEBUG: Received Message={'type': 1, 'content': {'task_id': 'schedule_collector', 'status': 16, 'output': None, 'stop_datetime': da...
 DEBUG: Pushing task to the worker queue            
 DEBUG: {'worker_name': 'collector', 'options': {'address': '0.0.0.0', 'port': 2345, 'key': 'key_for_agent'}, 'status': 2, 'start_d...
 DEBUG: Add Task 8ed2242c to worker 'collector' queue
 DEBUG: Startin new worker temboardui.plugins.monitoring._tm_wrapper_collector
 DEBUG: Received Message={'type': 1, 'content': {'task_id': '8ed2242c', 'status': 4}}
  INFO: Starting collector for 0.0.0.0:2345.                                                                                       
  INFO: Discovering hostname from agent 0.0.0.0:2345.
 DEBUG: Calling https://0.0.0.0:2345/discover.
 DEBUG: Received Message={'type': 1, 'content': {'task_id': '8ed2242c', 'status': 8}}                                              
 DEBUG: {'hostname': 'postgres.dev', 'cpu': 8, 'memory_size': 16418099200, 'pg_port': 5432, 'pg_version': 'PostgreSQL 14.1 on x86_6...
  INFO: Found host #1 and instance #1 for agent 0.0.0.0:2345, hostname postgres.dev. 
  INFO: Querying monitoring history from agent 0.0.0.0:2345.                                                                       
 DEBUG: Calling https://0.0.0.0:2345/monitoring/history?key=key_for_agent&limit=100&start=2021-12-23T13:19:34Z.
  INFO: Update the inventory for 0.0.0.0:2345.       
  INFO: Insert instance availability for 0.0.0.0:2345.
  INFO: Insert collected metrics for 0.0.0.0:2345.                                                                                 
 DEBUG: Update collector status for agent 0.0.0.0:2345.                                                                            
  INFO: Populate checks for host: postgres.dev.
  INFO: Apply alerting checks against preprocessed data for agent 0.0.0.0:2345.     
```

### CODE REVIEW

**Comment by wahyubudiman** [comment]
Hi @bersace , how to apply this patch for issue #952 ?

**Comment by bersace** [comment]
@wahyubudiman 7.9 release is imminent. Could you wait for it ?

**Comment by bersace** [comment]
@wahyubudiman you can already download rpm for temBoard 7.9. We're writing news post.

**Comment by wahyubudiman** [comment]
hi @bersace , it's only for temboard server or include agent to?

**Comment by bersace** [comment]
Hi @wahyubudiman both agent and UI have a dedicated patch to improve monitoring messages.

**Pull request merged**
