### PR TITLE
Alerting pages

### PR DESCRIPTION
**Pull request by pgiraud**

### CODE REVIEW

**Comment by pgiraud** [comment]
localhost_8888_home laptop with mdpi screen
localhost_8888_server_0 0 0 0_2345_dashboard laptop with mdpi screen 1
localhost_8888_server_0 0 0 0_2345_alerting_load1 laptop with mdpi screen

**Comment by pgiraud** [comment]
I removed the WIP flag since it's stable enough for review.

What's missing in my opinion :
- [ ] we should merge cpu_core keys into one. It doesn't make sense to show every single cpu unit.
- [ ] a check should be made each time the thresholds are updated instead of waiting for the next scheduled one.
- [ ] keep the selected time range when switching from one check page to an other
- [ ] add a link to monitoring page with corresponding chart and time range selected
- [ ] show thresholds in the memory usage chart (not easy because of the mix between byte values and percentage)
- [ ] in alerts list (dashboard) add indication whether the state is back to normal

**Comment by julmon** [comment]
Hi,

I'm experiencing a bug on dashboard page when the number of items in `Last Alerts` list is lower to 3: tooltip seems to be at wrong place. Please see the screenshot below.
bug-alerting1

**Comment by julmon** [comment]
When no ongoing alerts, we should probably be more verbose on the home page, having just `OK` is not very meaningful.
bug-alerting2

**Comment by pgiraud** [comment]
> I'm experiencing a bug on dashboard page when the number of items in Last Alerts list is lower to 3: tooltip seems to be at wrong place. Please see the screenshot below.

Taken into account.

**Comment by pgiraud** [comment]
> When no ongoing alerts, we should probably be more verbose on the home page, having just OK is not very meaningful.

Changed to this:
capture du 2018-06-12 13-48-39

**Pull request merged**
