### PR TITLE
update PostgreSQL version for docker demo

### PR DESCRIPTION
**Pull request by madtibo**
Update the docker demo to use supported PostgreSQL versions.

### CODE REVIEW

**Comment by madtibo** [comment]
I did not add a fifth PG instance to test on all supported versions.
There had to be one version not started and I arbitrarily chose to not start a PG 11 instance.
We could either add a PG 11 instance or change the 9.6 to 11, as you wish.

**Review by dlax — APPROVED** [review]
The second commit is related to your other PR #892; can you move it there?

Otherwise, changes about pg version look good to me.

**Comment by madtibo** [comment]
@dlax you are right, I corrected it.

**Comment by dlax** [comment]
You need to remove the *commit* not the file. So `git reset --hard e0f5542` on that branch and then force-push.

**Comment by madtibo** [comment]
done

**Comment by dlax** [comment]
Merged, thanks.

**Pull request merged**
