### PR TITLE
Configure SSL ciphers

### PR DESCRIPTION
**Pull request by bersace**
closes: #1239

### CODE REVIEW

**Comment by bersace** [comment]
@vvitad Is this good for you ?

**Review by pirlgon — APPROVED** [review]

**Comment by vvitad** [comment]
@bersace should there be `!DES` too?

**Comment by bersace** [comment]
> @bersace should there be `!DES` too?

I'm not a security expert, I need a recommendation for this.

I updated the patch to use Mozilla SSL configuration recommendation from https://ssl-config.mozilla.org/#server=postgresql&version=12.1&config=intermediate&openssl=1.1.1k&guideline=5.7. Let's see if e2e tests are happy with this.

**Comment by bersace** [comment]
Mozilla configuration matches SSL.com recommendations . https://www.ssl.com/guide/ssl-best-practices/#ftoc-heading-4

**Pull request merged**
